project_id = "yxlapjuovrsvjswkwnrk"

[functions.stripe-webhook]
  entrypoint = "./functions/stripe-webhook/index.ts"

[functions.apply-promo]
  entrypoint = "./functions/apply-promo/index.ts"
  verify_jwt = false
